### ISSUE TITLE
Remove the manditory need for API keys

### ISSUE THREAD

**Issue by zackjohnson8** [zackjohnson8/StockWatch#50]
To run StockWatch you need a set of TDAmeritrade and Reddit account tokens. Instead of doing it like this, warn the user in the logs that the functionality won't work until config files are adjusted appropriately. I want a minimal viable product that requires only downloading and running.

**Comment by regholl** [comment]
here i come to ruin your day but i'll give you the good news first...i
successfully created databases in docker......and thats all

2022-12-02 10:48:24,218-ERROR-root::config|27:: Unsupported platform win32
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\configparser.py", line 846, in items
    d.update(self._sections[section])
KeyError: 'stock_watch_bot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in
_run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\StockWatch-1\src\stock_watch\__main__.py", line 16, in <module>
    main()
  File "E:\StockWatch-1\src\stock_watch\__main__.py", line 11, in main
    stock_watch.run()
  File "E:\StockWatch-1\src\stock_watch\app.py", line 48, in run
    reddit_scraper = data_scraper.scrapers.reddit_scraper.RedditScraper()
  File
"E:\StockWatch-1\src\stock_watch\data_scraper\scrapers\reddit_scraper.py",
line 15, in __init__
    self._reddit_api = reddit_api.RedditAPI(site_name="stock_watch_bot")
  File "E:\StockWatch-1\src\stock_watch\data_scraper\apis\reddit_api.py",
line 50, in __init__
    self._reddit_api = praw.Reddit(
  File
"E:\StockWatch-1\venv\lib\site-packages\praw\util\deprecate_args.py", line
43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "E:\StockWatch-1\venv\lib\site-packages\praw\reddit.py", line 236,
in __init__
    self.config = Config(
  File "E:\StockWatch-1\venv\lib\site-packages\praw\config.py", line 84, in
__init__
    self.custom = dict(Config.CONFIG.items(site_name), **settings)
  File "C:\Program Files\Python39\lib\configparser.py", line 849, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'stock_watch_bot'
You provided the name of a praw.ini configuration which does not exist.

**Comment by regholl** [comment]
windows 11 with python 3.9.12 on visual studio code.....i'm going to
download pycharm and see if i have better luck working with it

**Comment by zackjohnson8** [comment]
Oh don't worry, this is a bug with data_scraper/config/config.py in the function copy_praw_ini_file_to_platform_folder. While I'm working on this section, I'll add that fix in there, but if you'd like to keep working on it you can make the change locally until then. You see in the top of your logs where it says Unsupported platform win32. That's the reason you're having this issue. I've only implemented linux.

**Comment by zackjohnson8** [comment]
Hey @regholl , I've also updated the section you were having problems with in this issue fix.
