### ISSUE TITLE
multiple problems

### ISSUE THREAD

**Issue by regholl** [zackjohnson8/StockWatch#63]
i dont know what happened but this is a big throwback for me.

2022-12-16 08:47:34,754-INFO-root::app|21:: Starting StockWatch
2022-12-16 08:47:34,794-INFO-root::cli|20:: Running command: <src.stock_watch.docker.models.docker_compose_command.DockerComposeCommand object at 0x000001CF7117C4F0>
Beginning work on chunk 1/1
Started: ('docker-compose -f ./src\\stock_watch\\docker\\database\\docker-compose-database.yml   up --build --force-recreate --detach ',), pid=12532
Failed: ('docker-compose -f ./src\\stock_watch\\docker\\database\\docker-compose-database.yml   up --build --force-recreate --detach ',), pid=12532, result: 'docker-compose' is not recognized as an internal or external command,
operable program or batch file.
Completed work on chunk 1/1
2022-12-16 08:47:34,815-INFO-root::reddit_scraper|33:: Starting RedditScraper
2022-12-16 08:47:34,958-INFO-root::reddit_scraper|54:: Starting the retrieval loop for the RedditScraper...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "E:\StockWatch\src\stock_watch\__init__.py", line 36, in <module>
    message_bus = MessageBus.get_instance()
  File "E:\StockWatch\src\stock_watch\message_bus\message_bus.py", line 20, in get_instance
    MessageBus()
  File "E:\StockWatch\src\stock_watch\message_bus\message_bus.py", line 41, in __init__
    self.message_process.start()
  File "E:\StockWatch\src\stock_watch\message_bus\message_bus_process.py", line 29, in start
    return super().start()
  File "C:\Program Files\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python310\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python310\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python310\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\StockWatch\src\stock_watch\__main__.py", line 12, in <module>
    main()
  File "E:\StockWatch\src\stock_watch\__main__.py", line 7, in main
    stock_watch.run()
  File "E:\StockWatch\src\stock_watch\app.py", line 51, in run
    self.data_scraper_service.start_scrapers()
  File "E:\StockWatch\src\stock_watch\data_scraper\data_scraper_service.py", line 35, in start_scrapers
    self._process_manager.start_all_processes()
  File "E:\StockWatch\src\stock_watch\data_scraper\process_manager.py", line 25, in start_all_processes
    process.start()
  File "E:\StockWatch\src\stock_watch\data_scraper\scraper_process.py", line 23, in start
    self._process = multiprocessing.Process(target=self._scraper.start())
  File "E:\StockWatch\src\stock_watch\data_scraper\scrapers\reddit_scraper.py", line 40, in start
    self._start_retrieval_loop()
  File "E:\StockWatch\src\stock_watch\data_scraper\scrapers\reddit_scraper.py", line 60, in _start_retrieval_loop
    for subreddit in followed_subreddits:
  File "E:\StockWatch\venv\lib\site-packages\praw\models\listing\generator.py", line 63, in __next__
    self._next_batch()
  File "E:\StockWatch\venv\lib\site-packages\praw\models\listing\generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "E:\StockWatch\venv\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "E:\StockWatch\venv\lib\site-packages\praw\reddit.py", line 634, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "E:\StockWatch\venv\lib\site-packages\praw\reddit.py", line 739, in _objectify_request
    self.request(
  File "E:\StockWatch\venv\lib\site-packages\praw\util\deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "E:\StockWatch\venv\lib\site-packages\praw\reddit.py", line 941, in request
    return self._core.request(
  File "E:\StockWatch\venv\lib\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "E:\StockWatch\venv\lib\site-packages\prawcore\sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "E:\StockWatch\venv\lib\site-packages\prawcore\sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "E:\StockWatch\venv\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "E:\StockWatch\venv\lib\site-packages\prawcore\sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "E:\StockWatch\venv\lib\site-packages\prawcore\auth.py", line 425, in refresh
    self._request_token(
  File "E:\StockWatch\venv\lib\site-packages\prawcore\auth.py", line 158, in _request_token
    raise OAuthException(
prawcore.exceptions.OAuthException: unauthorized_client error processing request (Only script apps may use password auth)
(venv) PS E:\StockWatch> python  -m src.stock_watch            
2022-12-16 08:51:09,127-INFO-root::app|21:: Starting StockWatch
2022-12-16 08:51:09,178-INFO-root::cli|20:: Running command: <src.stock_watch.docker.models.docker_compose_command.DockerComposeCommand object at 0x000001B05D59E1D0>
Beginning work on chunk 1/1
Started: ('docker-compose -f ./src\\stock_watch\\docker\\database\\docker-compose-database.yml   up --build --force-recreate --detach ',), pid=8620
Failed: ('docker-compose -f ./src\\stock_watch\\docker\\database\\docker-compose-database.yml   up --build --force-recreate --detach ',), pid=8620, result: 'docker-compose' is not recognized as an internal or external command,
operable program or batch file.
Completed work on chunk 1/1
2022-12-16 08:51:09,197-INFO-root::reddit_scraper|33:: Starting RedditScraper
2022-12-16 08:51:09,203-INFO-root::reddit_scraper|54:: Starting the retrieval loop for the RedditScraper...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "E:\StockWatch\src\stock_watch\__init__.py", line 36, in <module>
    message_bus = MessageBus.get_instance()
  File "E:\StockWatch\src\stock_watch\message_bus\message_bus.py", line 20, in get_instance
    MessageBus()
  File "E:\StockWatch\src\stock_watch\message_bus\message_bus.py", line 41, in __init__
    self.message_process.start()
  File "E:\StockWatch\src\stock_watch\message_bus\message_bus_process.py", line 29, in start
    return super().start()
  File "C:\Program Files\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python310\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python310\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python310\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\StockWatch\src\stock_watch\__main__.py", line 12, in <module>
    main()
  File "E:\StockWatch\src\stock_watch\__main__.py", line 7, in main
    stock_watch.run()
  File "E:\StockWatch\src\stock_watch\app.py", line 51, in run
    self.data_scraper_service.start_scrapers()
  File "E:\StockWatch\src\stock_watch\data_scraper\data_scraper_service.py", line 35, in start_scrapers
    self._process_manager.start_all_processes()
  File "E:\StockWatch\src\stock_watch\data_scraper\process_manager.py", line 25, in start_all_processes
    process.start()
  File "E:\StockWatch\src\stock_watch\data_scraper\scraper_process.py", line 23, in start
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "E:\StockWatch\venv\lib\site-packages\praw\reddit.py", line 941, in request
    return self._core.request(
  File "E:\StockWatch\venv\lib\site-packages\prawcore\sessions.py", line 330, in request
    return self._request_with_retries(
  File "E:\StockWatch\venv\lib\site-packages\prawcore\sessions.py", line 228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "E:\StockWatch\venv\lib\site-packages\prawcore\sessions.py", line 185, in _make_request
    response = self._rate_limiter.call(
  File "E:\StockWatch\venv\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "E:\StockWatch\venv\lib\site-packages\prawcore\sessions.py", line 283, in _set_header_callback
    self._authorizer.refresh()
  File "E:\StockWatch\venv\lib\site-packages\prawcore\auth.py", line 425, in refresh
    self._request_token(
  File "E:\StockWatch\venv\lib\site-packages\prawcore\auth.py", line 155, in _request_token
    response = self._authenticator._post(url, **data)
  File "E:\StockWatch\venv\lib\site-packages\prawcore\auth.py", line 38, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response

**Comment by zackjohnson8** [comment]
Are you on the same machine and os you were on previously? Let's break this down and see what we've got here.

**Comment by zackjohnson8** [comment]
Related to issue three, https://stackoverflow.com/questions/50973516/trying-to-scrape-reddit-with-praw-reddit. This could be an issue with the type of application you've created on https://www.reddit.com/prefs/apps/.
![image](https://user-images.githubusercontent.com/18540777/208142929-a0177630-a772-4cbd-87f8-c19dd967b5a8.png)
![image](https://user-images.githubusercontent.com/18540777/208143008-8bd9c18b-9749-4745-8dd0-fde4bbb732a8.png)

**Comment by regholl** [comment]
yep ,except i upgraded to python 3.10

**Comment by zackjohnson8** [comment]
Same IDE too? Not sure if it matters but are you creating a venv too.

**Comment by regholl** [comment]
yes thats what i have for reddit

**Comment by regholl** [comment]
yes on that also....once i create the app do i need to go to a
separate page to register it/?

**Comment by zackjohnson8** [comment]
You should just see something like this.
![image](https://user-images.githubusercontent.com/18540777/208144038-09f5a630-3f34-4b5c-8e60-1626762f96c8.png)

**Comment by zackjohnson8** [comment]
The client_id is the information below the 'personal use script' at the top. The client_secret is the secret. I named my user_agent 'stock-watch by u/zack_stock_watch_bot' but I don't think that matters. Then the user name and password are just your reddit accounts.

**Comment by regholl** [comment]
that all looks good

**Comment by zackjohnson8** [comment]
I'm stumped then. You shouldn't be getting 'prawcore.exceptions.OAuthException: unauthorized_client error processing request (Only script apps may use password auth)' with a personal use script. I mean that section says (Only script apps may use password auth). What you could try doing is creating another developed applications and see if that fixes it. Otherwise, that's really as far as I can go. My hands are tied when it comes to everything here except the freeze_support() method call.

**Comment by regholl** [comment]
got ya,i'll try the new app and if that doest work i'll do a python
downgrade cause thats where it all began.ty

**Comment by zackjohnson8** [comment]
Perfect, I'll the removal of freeze_support into the main branch until I can look into it more. It shouldn't be a problem with python 3.10 since that's what I'm developing on. It could have been an issue with how it got upgraded though.
![image](https://user-images.githubusercontent.com/18540777/208149947-92de8fa6-60c1-433c-889d-32e8fcf938f9.png)

**Comment by regholl** [comment]
yeah i have a bad history with python and getting it mangled.plus there are
many opinions on how it should be done.some say install for all users and
others say only you,others say install it using run admin ,others dont

**Comment by zackjohnson8** [comment]
I wonder if it's a problem with venv only remembering the python it was initially setup with. 
https://stackoverflow.com/questions/10218946/upgrade-python-in-a-virtualenv
https://stackoverflow.com/questions/2170252/can-existing-virtualenv-be-upgraded-gracefully

**Comment by regholl** [comment]
i might have found the hangup.i went to powershell and ran virtualenv
--version.......nothing not recognized.

**Comment by zackjohnson8** [comment]
Don't be shy about keeping me updated on the fix you find. This is a good learning experience for the two of us. I'd assume that virtualenv is a part of python installation. I assume when you type python --version you're getting Python 3.10.6, right?

**Comment by regholl** [comment]
well that was part of it,now im left with

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 187, in
_run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\Python310\lib\runpy.py", line 146, in
_get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Program Files\Python310\lib\runpy.py", line 110, in
_get_module_details
    __import__(pkg_name)
  File "E:\StockWatch\src\stock_watch\__init__.py", line 4, in <module>
    from . import data_scraper
  File "E:\StockWatch\src\stock_watch\data_scraper\__init__.py", line 4, in
<module>
    from . import scrapers
  File "E:\StockWatch\src\stock_watch\data_scraper\scrapers\__init__.py",
line 4, in <module>
    from . import reddit_scraper
  File
"E:\StockWatch\src\stock_watch\data_scraper\scrapers\reddit_scraper.py",
line 4, in <module>
    from ..apis import reddit_api
  File "E:\StockWatch\src\stock_watch\data_scraper\apis\__init__.py", line
4, in <module>
    from . import reddit_api
  File "E:\StockWatch\src\stock_watch\data_scraper\apis\reddit_api.py",
line 2, in <module>
    from praw.util.token_manager import BaseTokenManager
ModuleNotFoundError: No module named 'praw'

**Comment by zackjohnson8** [comment]
Oh good, you could be getting this from not running 'pip install -r requirements.txt' after activating your venv.

**Comment by regholl** [comment]
i don't believe it!!!it went right back to the original problem after i ran
pip install -r requirements

2022-12-16 11:24:06,915-INFO-root::app|21:: Starting StockWatch
2022-12-16 11:24:06,964-INFO-root::cli|20:: Running command:
<src.stock_watch.docker.models.docker_compose_command.DockerComposeCommand
object at 0x0000024F5E32E290>
Beginning work on chunk 1/1
Started: ('docker-compose -f
./src\\stock_watch\\docker\\database\\docker-compose-database.yml   up
--build --force-recreate --detach ',), pid=16132
Failed: ('docker-compose -f
./src\\stock_watch\\docker\\database\\docker-compose-database.yml   up
--build --force-recreate --detach ',), pid=16132, result: 'docker-compose'
is not recognized as an internal or external command,
operable program or batch file.
Completed work on chunk 1/1
2022-12-16 11:24:06,992-INFO-root::reddit_scraper|33:: Starting
RedditScraper
2022-12-16 11:24:06,998-INFO-root::reddit_scraper|54:: Starting the
retrieval loop for the RedditScraper...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 116,
in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 126,
in _main
    self = reduction.pickle.load(from_parent)
  File "E:\StockWatch\src\stock_watch\__init__.py", line 36, in <module>
    message_bus = MessageBus.get_instance()
  File "E:\StockWatch\src\stock_watch\message_bus\message_bus.py", line 20,
in get_instance
    MessageBus()
  File "E:\StockWatch\src\stock_watch\message_bus\message_bus.py", line 41,
in __init__
    self.message_process.start()
  File "E:\StockWatch\src\stock_watch\message_bus\message_bus_process.py",
line 29, in start
    return super().start()
  File "C:\Program Files\Python310\lib\multiprocessing\process.py", line
121, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python310\lib\multiprocessing\context.py", line
224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python310\lib\multiprocessing\context.py", line
327, in _Popen
    return Popen(process_obj)
  File "C:\Program
Files\Python310\lib\multiprocessing\popen_spawn_win32.py", line 45, in
__init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 154,
in get_preparation_data
    _check_not_importing_main()
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 134,
in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in
_run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\StockWatch\src\stock_watch\__main__.py", line 12, in <module>
    main()
  File "E:\StockWatch\src\stock_watch\__main__.py", line 7, in main
    stock_watch.run()
  File "E:\StockWatch\src\stock_watch\app.py", line 51, in run
    self.data_scraper_service.start_scrapers()
  File
"E:\StockWatch\src\stock_watch\data_scraper\data_scraper_service.py", line
35, in start_scrapers
  File "E:\StockWatch\venv\lib\site-packages\prawcore\sessions.py", line
330, in request
    return self._request_with_retries(
  File "E:\StockWatch\venv\lib\site-packages\prawcore\sessions.py", line
228, in _request_with_retries
    response, saved_exception = self._make_request(
  File "E:\StockWatch\venv\lib\site-packages\prawcore\sessions.py", line
185, in _make_request
    response = self._rate_limiter.call(
  File "E:\StockWatch\venv\lib\site-packages\prawcore\rate_limit.py", line
33, in call
    kwargs["headers"] = set_header_callback()
  File "E:\StockWatch\venv\lib\site-packages\prawcore\sessions.py", line
283, in _set_header_callback
    self._authorizer.refresh()
  File "E:\StockWatch\venv\lib\site-packages\prawcore\auth.py", line 425,
in refresh
    self._request_token(
  File "E:\StockWatch\venv\lib\site-packages\prawcore\auth.py", line 158,
in _request_token
    raise OAuthException(
prawcore.exceptions.OAuthException: invalid_grant error processing request

**Comment by zackjohnson8** [comment]
Almost the same actually. New prawcore issue at the bottom. I've removed the freeze_support line from the main code if you wanted to pull the most recent version. Lastly, we just need to figure out what's going on with your docker.

**Comment by zackjohnson8** [comment]
type docker --version into your terminal

**Comment by zackjohnson8** [comment]
![image](https://user-images.githubusercontent.com/18540777/208155474-2802756d-4fdd-4dd7-8fd5-ea5bbe5c0c78.png)

**Comment by regholl** [comment]
got it,i gotta make a trip to the store while its not a blizzard
outside.give me chance to for my anxiety to go down and comeback with a
fresh mind

**Comment by zackjohnson8** [comment]
Sounds good, we're getting closer. Don't let that anxiety hit you too hard. I'm having a blast with all this.

**Comment by zackjohnson8** [comment]
Also it looks like they found a solution to the invalid_grant error processing request. The solution in the link is to make sure your Reddit account is registered as a developer account.

https://www.reddit.com/r/redditdev/comments/fkfjr9/prawcoreexceptionsoauthexception_invalid_grant/

![image](https://user-images.githubusercontent.com/18540777/208156668-c8fcf365-e839-4307-a9e2-d7b8f6ef4e63.png)

**Comment by zackjohnson8** [comment]
Alright, I've fixed some of the issues Windows was having with the freeze_support and message_bus process not running correctly on Windows OS because of how it was being initialized. 
https://github.com/zackjohnson8/StockWatch/pull/64
